### ISSUE TITLE
Default print direction should be left-to-right, not right-to-left

### ISSUE THREAD

**Issue by acanda** [dtmo/jfiglet#1]
Fonts that do not have the print direction set in the header values are rendered right-to-left instead of left-to-right.

E.g. the font [Chunky](https://raw.githubusercontent.com/xero/figlet-fonts/master/Chunky.flf) does not have the print direction set in its header values and is rendered right-to-left.

**Comment by dtmo** [comment]
Hi, thanks for reporting this issue and for supplying a fix. I've merged your changes into master and will get a bugfix release out shortly.
